config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  root :to => "home#index"
  get 'home/index'
  
  resources :things
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
    # attr_accessible :title, :description, :content, :uri, :price, :created_at, :likes, :available_at, :discount, :is_available, :keywords, :slug

    validates :title,  :presence => true
    validates :description, :presence => true,
                      :length => { :minimum => 50 }
    validates :content, :presence => true,
                      :length => { :minimum => 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:title, :description, :content, :uri, :price, :created_at, :likes, :available_at, :discount, :is_available, :keywords, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h1>Hello, Rails!</h1>
<%= link_to "My Things", things_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiracleDrugs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_with(model: thing, local: true) do |form| %>
  <% if thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :uri %>
    <%= form.text_field :uri %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes %>
  </div>

  <div class="field">
    <%= form.label :available_at %>
    <%= form.datetime_select :available_at %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :is_available %>
    <%= form.check_box :is_available %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_field :keywords %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Things</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Content</th>
      <th>Uri</th>
      <th>Price</th>
      <th>Created at</th>
      <th>Likes</th>
      <th>Available at</th>
      <th>Discount</th>
      <th>Is available</th>
      <th>Keywords</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.title %></td>
        <td><%= thing.description %></td>
        <td><%= thing.content %></td>
        <td><%= thing.uri %></td>
        <td><%= thing.price %></td>
        <td><%= thing.created_at %></td>
        <td><%= thing.likes %></td>
        <td><%= thing.available_at %></td>
        <td><%= thing.discount %></td>
        <td><%= thing.is_available %></td>
        <td><%= thing.keywords %></td>
        <td><%= thing.slug %></td>
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @thing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @thing.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @thing.content %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @thing.uri %>
</p>

<p>
  <strong>Price:</strong>
  <%= @thing.price %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @thing.created_at %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @thing.likes %>
</p>

<p>
  <strong>Available at:</strong>
  <%= @thing.available_at %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @thing.discount %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @thing.is_available %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @thing.keywords %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @thing.slug %>
</p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>